export { streamChatResponse, getChatResponse } from './client'
export type { ChatMessage, StreamChatOptions } from './client'
export { buildSystemPrompt, checkAfterHours } from './prompts'
export type { PracticeContext } from './prompts'
export { extractPatientInfo, mergePatientInfo } from './extract-info'
export type { ExtractedPatientInfo } from './extract-info'
